services:
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    container_name: 'mongodb_container' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db